//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class AppDelegate, NSMutableArray, NSTimer, UIBarButtonItem, UIButton, UITextView;

@interface AboutViewController : UIViewController
{
    AppDelegate *appDelegate;
    NSTimer *removeProfileTimer;
    NSMutableArray *weeklyTitleAry;
    UIBarButtonItem *_sidebarButton;
    UITextView *_useRuleTV;
    UIButton *_removeOldProfileBtn;
    UIButton *_removeProfileBtn1_3_2;
}

@property(nonatomic) __weak UIButton *removeProfileBtn1_3_2; // @synthesize removeProfileBtn1_3_2=_removeProfileBtn1_3_2;
@property(nonatomic) __weak UIButton *removeOldProfileBtn; // @synthesize removeOldProfileBtn=_removeOldProfileBtn;
@property(nonatomic) __weak UITextView *useRuleTV; // @synthesize useRuleTV=_useRuleTV;
@property(nonatomic) __weak UIBarButtonItem *sidebarButton; // @synthesize sidebarButton=_sidebarButton;
- (void).cxx_destruct;
- (void)removeOldIdProfileBtn:(id)arg1;
- (void)removeProfileBtn1_3_2Action:(id)arg1;
- (void)removeOldProfile;
- (void)swithToRemoveOldProfilePage;
- (void)swithToRemoveOldIdProfilePage;
- (void)swithToRemove1_3_2ProfilePage;
- (void)installRemoveOldIdProfile;
- (void)installRemoveOldProfile;
- (void)installRemove1_3_2Profile;
- (void)swithToInstallProfilePage;
- (void)installProfile;
- (void)autoLockAction:(id)arg1;
- (void)removeOldProfileBtnAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)changeDate:(id)arg1;
- (id)convertInsideValue:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

