//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AppDelegate, FMDatabase, MainViewController, NSMutableArray, NSString, UIAlertAction, UIAlertController, UIButton, UITableView;

@interface AdminViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    AppDelegate *appDelegate;
    FMDatabase *myDB;
    NSMutableArray *queryAllData;
    UIAlertController *checkGPSAlert;
    UIAlertAction *goGPSAction;
    MainViewController *mainVC;
    _Bool _testbool;
    UITableView *_adminQueryTable;
    UIButton *_installUnlockProfileBtn;
}

@property _Bool testbool; // @synthesize testbool=_testbool;
@property(nonatomic) __weak UIButton *installUnlockProfileBtn; // @synthesize installUnlockProfileBtn=_installUnlockProfileBtn;
@property(nonatomic) __weak UITableView *adminQueryTable; // @synthesize adminQueryTable=_adminQueryTable;
- (void).cxx_destruct;
- (void)switchToLocationSettingPage;
- (void)deleteProfile;
- (void)swithToUnInstallProfilePage;
- (void)uninstallProfile;
- (void)viewDidLayoutSubviews;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)installUnlockProfileAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

