//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAudioPlayer, NSTimer, UIApplication;

@interface BackgroundTask : NSObject
{
    unsigned long long bgTask;
    CDUnknownBlockType expirationHandler;
    NSTimer *timer;
    AVAudioPlayer *player;
    long long timerInterval;
    id target;
    SEL selector;
    UIApplication *myApp;
}

- (void).cxx_destruct;
- (void)player_stop;
- (void)player_start;
- (void)stopBackgroundTask;
- (_Bool)running;
- (void)stopAudio;
- (void)playAudio;
- (void)audioInterrupted:(id)arg1;
- (void)initBackgroundTask;
- (void)startBackgroundTasks:(long long)arg1 target:(id)arg2 selector:(SEL)arg3 app:(id)arg4;
- (id)init;

@end

