//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BerTaggedObject : NSObject
{
    unsigned char berTag[1];
    id obj;
    unsigned long long start;
    unsigned long long end;
}

@property(nonatomic) unsigned long long end; // @synthesize end;
@property(nonatomic) unsigned long long start; // @synthesize start;
@property(retain, nonatomic) id obj; // @synthesize obj;
- (void).cxx_destruct;
- (id)berContentsDescription;
- (id)lengthStorageData;
- (id)berContents;
- (id)description;
- (id)descriptionFormat;
- (unsigned long long)berLengthBytes;
- (unsigned long long)berContentsLengthBytes;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic) unsigned char berTagValue;
- (char *)berTag;
- (id)unwrapped;
- (void)beMutable;

@end

