//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BerTaggedObject.h"

@class NSString;

@interface BerTaggedString : BerTaggedObject
{
}

- (unsigned long long)berContentsLengthBytes;
- (id)berData;
- (unsigned long long)berStringEncoding;
- (id)descriptionFormat;
@property(retain, nonatomic) NSString *string;

@end

