//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface CampModel : NSObject
{
    _Bool _isSelected;
    NSString *_title;
    NSString *_detail;
    NSString *_polygonString;
    NSDate *_signDate;
}

@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(copy, nonatomic) NSDate *signDate; // @synthesize signDate=_signDate;
@property(copy, nonatomic) NSString *polygonString; // @synthesize polygonString=_polygonString;
@property(copy, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

