//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FMDatabase, NSString, NSURL;

@interface DBObject : NSObject
{
    NSString *someProperty;
    FMDatabase *db;
    NSURL *appUrl;
    NSString *dbPath;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *someProperty; // @synthesize someProperty;
- (void).cxx_destruct;
- (void)dealloc;
- (id)getMyString;
- (void)queryRangeData:(id)arg1 andEndMillionsTime:(id)arg2;
- (void)insertData;
- (void)insertStatusLog:(id)arg1;
- (void)createTable;
- (id)init;

@end

