//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIBarButtonItem, UILabel;

@interface ElectronicTagViewController : UIViewController
{
    UIBarButtonItem *_sidebarButton;
    UILabel *_phoneTagLb;
    UILabel *_upPhoneTagLb;
}

@property(nonatomic) __weak UILabel *upPhoneTagLb; // @synthesize upPhoneTagLb=_upPhoneTagLb;
@property(nonatomic) __weak UILabel *phoneTagLb; // @synthesize phoneTagLb=_phoneTagLb;
@property(nonatomic) __weak UIBarButtonItem *sidebarButton; // @synthesize sidebarButton=_sidebarButton;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

