//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GetSiteInfo : NSObject
{
}

+ (id)genRandStr:(int)arg1;
+ (id)base64DecodeString:(id)arg1;
+ (id)parseSite:(id)arg1 andResponse:(id)arg2 andError:(id)arg3;
- (id)base64EncodeString:(id)arg1;

@end

