//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIApplicationDelegate.h"

@class HTTPServer, NSString, UIWindow, iPhoneHTTPServerViewController;

@interface iPhoneHTTPServerAppDelegate : NSObject <UIApplicationDelegate>
{
    HTTPServer *httpServer;
    UIWindow *window;
    iPhoneHTTPServerViewController *viewController;
}

@property(retain, nonatomic) iPhoneHTTPServerViewController *viewController; // @synthesize viewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window;
- (void).cxx_destruct;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)startServer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

