//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface KeyChainUtil : NSObject
{
}

+ (void)cleanKeychainData:(id)arg1 andGroupName:(id)arg2;
+ (void)storeKeyChainKey:(id)arg1 andValue:(id)arg2 andGroup:(id)arg3;
+ (id)readKeyChainKey:(id)arg1 andGroup:(id)arg2;

@end

