//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface LogUpdateTableViewCell : UITableViewCell
{
    UILabel *_logStatusNumber;
    UILabel *_logStatusContent;
    UILabel *_logStatusAriseTime;
    UILabel *_logStatusLock;
}

@property(nonatomic) __weak UILabel *logStatusLock; // @synthesize logStatusLock=_logStatusLock;
@property(nonatomic) __weak UILabel *logStatusAriseTime; // @synthesize logStatusAriseTime=_logStatusAriseTime;
@property(nonatomic) __weak UILabel *logStatusContent; // @synthesize logStatusContent=_logStatusContent;
@property(nonatomic) __weak UILabel *logStatusNumber; // @synthesize logStatusNumber=_logStatusNumber;
- (void).cxx_destruct;

@end

