//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MDM_RSA : NSObject
{
}

+ (id)decryptRSAKeyWithType:(struct rsa_st *)arg1 encryptedData:(id)arg2 paddingType:(int)arg3;
+ (id)decryptRSA:(id)arg1 type:(int)arg2 modulus:(id)arg3 exponent:(id)arg4;

@end

