//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface MdmFmdb : NSObject
{
    NSString *userName;
    NSNumber *lockStatus;
    NSNumber *event;
    NSNumber *lastUploadTimestamp;
    NSNumber *updateTimestamp;
    NSString *description;
    NSString *campName;
    NSString *campPolygon;
}

+ (void)dumpQueryResult:(id)arg1;
+ (id)convertDatetimeToString:(id)arg1;
+ (id)convertStringToDatetime:(id)arg1;
+ (id)convertNSDateToNSNumber:(id)arg1;
+ (id)convertNSNumberToNSDate:(id)arg1;
+ (id)convertResultToArray:(id)arg1 tableName:(id)arg2;
+ (int)getRowCount:(id)arg1 tableName:(id)arg2;
+ (id)queryAllDesc:(id)arg1 tableName:(id)arg2;
+ (id)queryAll:(id)arg1 tableName:(id)arg2;
+ (id)queryByUpdateDateDesc:(id)arg1 tableName:(id)arg2 from:(id)arg3 to:(id)arg4;
+ (id)queryByUpdateDate:(id)arg1 tableName:(id)arg2 from:(id)arg3 to:(id)arg4;
+ (id)queryByLastuploadDate:(id)arg1 tableName:(id)arg2 from:(id)arg3 to:(id)arg4;
+ (id)queryByLastuploadTimeRange:(id)arg1 tableName:(id)arg2 ago:(int)arg3;
+ (id)queryByUpdateTimeRange:(id)arg1 tableName:(id)arg2 ago:(int)arg3;
+ (id)queryByName:(id)arg1 tableName:(id)arg2 name:(id)arg3;
+ (void)updateByUpdateTimestamp:(id)arg1 tableName:(id)arg2 newValue:(id)arg3;
+ (void)updateByName:(id)arg1 tableName:(id)arg2 newValue:(id)arg3;
+ (void)insertData:(id)arg1 tableName:(id)arg2 aRecord:(id)arg3 isReplaced:(_Bool)arg4;
+ (void)addRecord:(id)arg1 tableName:(id)arg2 name:(id)arg3 polygon:(id)arg4 update:(id)arg5;
+ (void)addRecord:(id)arg1 tableName:(id)arg2 name:(id)arg3 event:(id)arg4 status:(id)arg5 upload:(id)arg6 update:(id)arg7 description:(id)arg8;
+ (void)delOldRecord:(id)arg1 tableName:(id)arg2;
+ (void)delRecodeFromDb:(id)arg1 andTableName:(id)arg2 andValue:(id)arg3;
+ (void)dropTable:(id)arg1 tableName:(id)arg2;
+ (void)createTable:(id)arg1 tableName:(id)arg2;
+ (id)getFMDatabase:(id)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)setcampPolygon:(id)arg1;
- (id)getcampPolygon;
- (void)setcampName:(id)arg1;
- (id)getcampName;
- (void)setLockStatus:(id)arg1;
- (id)getLockStatus;
- (void)setDescription:(id)arg1;
- (id)getDescription;
- (void)setUpdateTimestamp:(id)arg1;
- (id)getUpdateTimestamp;
- (void)setUploadTimestamp:(id)arg1;
- (id)getUploadTimestamp;
- (void)setEvent:(id)arg1;
- (id)getEvent;
- (void)setName:(id)arg1;
- (id)getName;

@end

