//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AVCaptureMetadataOutputObjectsDelegate.h"

@class AVCaptureSession, AVCaptureVideoPreviewLayer, AppDelegate, FMDatabase, NSMutableArray, NSString, UIAlertAction, UIAlertController, UIBarButtonItem, UINavigationController, UIStoryboard, UIView;

@interface NewCampLockQRCodeViewController : UIViewController <AVCaptureMetadataOutputObjectsDelegate>
{
    AppDelegate *appDelegate;
    FMDatabase *myDB;
    NSString *cutqrcodeStr;
    NSMutableArray *QRcodeQueryAllData;
    _Bool isReading;
    UIAlertController *qrcodeAlertController;
    UIAlertAction *qrCodeHintOkAc;
    UIStoryboard *storyboard;
    UINavigationController *rootMainViewController;
    UIAlertController *licenseTimeOutAlertController;
    UIAlertController *dataErrorAlertController;
    UIAlertAction *dataErrorAlertControllerOKAc;
    _Bool _isReading;
    UIBarButtonItem *_sidebarButton;
    UIView *_viewPreview;
    AVCaptureSession *_captureSession;
    AVCaptureVideoPreviewLayer *_videoPreviewLayer;
}

@property(retain, nonatomic) AVCaptureVideoPreviewLayer *videoPreviewLayer; // @synthesize videoPreviewLayer=_videoPreviewLayer;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(nonatomic) __weak UIView *viewPreview; // @synthesize viewPreview=_viewPreview;
@property(nonatomic) __weak UIBarButtonItem *sidebarButton; // @synthesize sidebarButton=_sidebarButton;
@property(nonatomic) _Bool isReading; // @synthesize isReading=_isReading;
- (void).cxx_destruct;
- (void)swithToInstallProfilePage;
- (void)installProfile;
- (double)qrcode_decode:(id)arg1;
- (id)LKV2_transformTo_LOCK:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)stopReading;
- (void)startReading;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

