//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NewCampWifiModel : NSObject
{
    NSString *_siteNameTime;
    NSString *_r;
    NSString *_q;
    NSString *_s;
    NSString *_siteName;
    NSString *_siteRange;
    NSString *_status;
}

@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *siteRange; // @synthesize siteRange=_siteRange;
@property(copy, nonatomic) NSString *siteName; // @synthesize siteName=_siteName;
@property(copy, nonatomic) NSString *s; // @synthesize s=_s;
@property(copy, nonatomic) NSString *q; // @synthesize q=_q;
@property(copy, nonatomic) NSString *r; // @synthesize r=_r;
@property(copy, nonatomic) NSString *siteNameTime; // @synthesize siteNameTime=_siteNameTime;
- (void).cxx_destruct;

@end

