//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PointInPolygon : NSObject
{
}

+ (_Bool)isPointInPolygon:(struct CGPoint)arg1 passedPolygon:(id)arg2 andLocationAccuracy:(float)arg3 andUnlockMode:(long long)arg4;
+ (_Bool)isPointInPolygon:(struct CGPoint)arg1 andLocationAccuracy:(float)arg2 andUnlockMode:(long long)arg3;
+ (id)parseContentsOfPolygonList:(id)arg1;
+ (id)readFileForPolygonList;
+ (_Bool)isInside:(struct CGPoint)arg1 Polygons:(id)arg2;
+ (double)getLength:(struct CGPoint)arg1;
+ (double)cross:(struct CGPoint)arg1 and:(struct CGPoint)arg2;
+ (double)dot:(struct CGPoint)arg1 and:(struct CGPoint)arg2;
+ (double)pointDistance:(struct CGPoint)arg1 between:(struct CGPoint)arg2 and:(struct CGPoint)arg3;
+ (_Bool)isNearBoundary:(struct CGPoint)arg1 Polygons:(id)arg2 andLocationAccuracy:(float)arg3 andUnlockMode:(long long)arg4;

@end

