//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class AppDelegate, FMDatabase, MBProgressHUD, NSDate, NSDateFormatter, NSLocale, NSMutableArray, NSString, UIBarButtonItem, UIButton, UIDatePicker, UILabel, UITableView, UITextField;

@interface QueryViewController : UIViewController <UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UIDatePicker *datePicker;
    NSLocale *dateLocale;
    NSDateFormatter *dateFormatter;
    NSString *dateFormat;
    NSString *sysVerStr;
    long long currentSelectTFTag;
    NSDate *yesterDate;
    FMDatabase *myDB;
    NSMutableArray *result;
    MBProgressHUD *hud;
    AppDelegate *appDelegate;
    UIBarButtonItem *_sidebarButton;
    UITextField *_startTimeTF;
    UITextField *_endTimeTF;
    UIButton *_queryBtn;
    UITableView *_queryTableView;
    UILabel *_versionLb;
}

@property(nonatomic) __weak UILabel *versionLb; // @synthesize versionLb=_versionLb;
@property(nonatomic) __weak UITableView *queryTableView; // @synthesize queryTableView=_queryTableView;
@property(nonatomic) __weak UIButton *queryBtn; // @synthesize queryBtn=_queryBtn;
@property(nonatomic) __weak UITextField *endTimeTF; // @synthesize endTimeTF=_endTimeTF;
@property(nonatomic) __weak UITextField *startTimeTF; // @synthesize startTimeTF=_startTimeTF;
@property(nonatomic) __weak UIBarButtonItem *sidebarButton; // @synthesize sidebarButton=_sidebarButton;
- (void).cxx_destruct;
- (void)dismissKeyboard;
- (void)queryBtnTouchUpAction:(id)arg1;
- (void)queryBtnTouchDownAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)updateDateChanged:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)swithToInstallProfilePage;
- (void)installProfile;
- (void)autoLockAction:(id)arg1;
- (void)didTapOnTableView:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

