//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AppDelegate, CampModel, FMDatabase, NSIndexPath, NSMutableArray, NSString, UIAlertAction, UIAlertController, UIBarButtonItem, UIButton, UITableView;

@interface RecentCampViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    AppDelegate *appDelegate;
    long long selectedIndex;
    CampModel *campModel;
    CampModel *selectedModel;
    NSMutableArray *campMenuAry;
    FMDatabase *myDB;
    NSMutableArray *signHistoryResult;
    NSMutableArray *permanentResult;
    UIAlertController *alertController;
    UIAlertAction *alertAction;
    UIAlertController *licenseTimeOutAlertController;
    UIBarButtonItem *_sidebarButton;
    UITableView *_recentTable;
    NSIndexPath *_lastSelected;
    UIButton *_recentLockBtn;
}

@property(nonatomic) __weak UIButton *recentLockBtn; // @synthesize recentLockBtn=_recentLockBtn;
@property(retain, nonatomic) NSIndexPath *lastSelected; // @synthesize lastSelected=_lastSelected;
@property(nonatomic) __weak UITableView *recentTable; // @synthesize recentTable=_recentTable;
@property(nonatomic) __weak UIBarButtonItem *sidebarButton; // @synthesize sidebarButton=_sidebarButton;
- (void).cxx_destruct;
- (void)swithToInstallProfilePage;
- (void)installProfile;
- (void)autoLockAction:(id)arg1;
- (void)recentLockAction:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

