//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSONModel.h"

@class NSMutableArray;

@interface SpotCampModel : JSONModel
{
    NSMutableArray *_spotDataAry;
}

@property(retain, nonatomic) NSMutableArray *spotDataAry; // @synthesize spotDataAry=_spotDataAry;
- (void).cxx_destruct;

@end

