//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TransHardCodeData : NSObject
{
    NSString *transferSiteData;
    NSString *spotSiteData;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)getSpotSiteData;
- (id)getTransferSiteData;
- (id)init;

@end

