//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSONModel.h"

@class NSMutableArray;

@interface TransferCampModel : JSONModel
{
    NSMutableArray *_navyDataAry;
}

@property(retain, nonatomic) NSMutableArray *navyDataAry; // @synthesize navyDataAry=_navyDataAry;
- (void).cxx_destruct;

@end

